version: '3.8'

services:
  app:
    build: .
    image: 2fa-app:latest
    container_name: 2fa-app
    ports:
      - "5555:5555"
    volumes:
      - ./data:/app/backend/data
    environment:
      - NODE_ENV=production
      - PORT=5556
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
