version: '3.8'

services:
  backend:
    build: ./backend
    container_name: 2fa-backend
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_PATH=/app/data/2fa.db
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    networks:
      - 2fa-network

  frontend:
    build: ./frontend
    container_name: 2fa-frontend
    restart: unless-stopped
    ports:
      - "5555:80"
    depends_on:
      - backend
    networks:
      - 2fa-network

networks:
  2fa-network:
    driver: bridge

volumes:
  data:

